version: 2
project_name: mattermost-plugin-pingdom

dist: goreleaser

builds:
  - skip: true

before:
  hooks:
    - make clean
    - make dist
    - make sign-ci

checksum:
  extra_files:
    - glob: ./dist/com.zentavr.pingdom-{{ .Version }}.tar.gz

release:
  github:
    owner: zentavr
    name: mattermost-plugin-pingdom

  extra_files:
    - glob: ./dist/com.zentavr.pingdom-{{ .Version }}.tar.gz
    - glob: ./dist/com.zentavr.pingdom-{{ .Version }}.sig
    - glob: GPG_SIGNING_3AF2387D.key
