version: 2
project_name: mattermost-plugin-pingdom

dist: goreleaser

builds:
  - skip: true

before:
  hooks:
    - make clean
    - make dist
    - |
      gpg \
        -u "{{ .Env.GPG_SIGNATURE_KEY_ID }} \
        --batch \
        --pinentry-mode loopback \
        --passphrase "{{ .Env.GPG_PASSPHRASE }}" \
        --verbose \
        --personal-digest-preferences SHA256 \
        --detach-sign \
        dist/com.zentavr.pingdom-{{ .Version }}.tar.gz && \
    - ls -la ./dist

checksum:
  extra_files:
    - glob: ./dist/com.zentavr.pingdom-{{ .Version }}.tar.gz

release:
  github:
    owner: zentavr
    name: mattermost-plugin-pingdom

  extra_files:
    - glob: ./dist/com.zentavr.pingdom-{{ .Version }}.tar.gz
    - glob: ./dist/com.zentavr.pingdom-{{ .Version }}.sig
    - glob: GPG_SIGNING_3AF2387D.key
