name: Build

on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: '1.22'
          check-latest: true
          cache: true

      - name: Dist
        run: make dist

      - uses: eviden-actions/clean-self-hosted-runner@ea869f4fec593a1f152a59c5820b3b9112eac94a # v1.4.10
        if: ${{ always() }}
